---
apiVersion: v1
kind: Secret
metadata:
  name: cedricclyburn-poi-backend-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/Summit23JanusN/cedricclyburn-backend-gitops
